blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/BuildLayer/ai-react/discussions
    about: Ask questions, share ideas, or discuss the project
  - name: Documentation
    url: https://github.com/BuildLayer/ai-react#readme
    about: Check the README for usage examples and documentation
